apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
  annotations:
    TOOLCHAIN_ID: {{ .Values.annotations.TOOLCHAIN_ID }}
    GIT_URL: {{ .Values.annotations.GIT_URL }}
    GIT_BRANCH: {{ .Values.annotations.GIT_BRANCH }}
    GIT_COMMIT: {{ .Values.annotations.GIT_COMMIT }}
    USER_NAME: {{ .Values.annotations.USER_NAME }}
    APPLICATION_VERSION: {{ .Values.annotations.APPLICATION_VERSION }}
    # Updates deployment when ConfigMaps or Secrets change
    checksum/configmap-app: {{ include (print $.Template.BasePath "/configmap-app.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        volumeMounts:
            - name: {{ include "chart.name" . }}-app-config-volume
              mountPath: "/whuser/config/config.json"
              subPath: "config.json"
        livenessProbe:
            httpGet:
                path: /gateway-listener/api/v1/live
                port: {{ .Values.service.internalPort }}
                scheme: HTTPS
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 60
        envFrom:
        - secretRef:
            name: {{ template "chart.fullname" . }}-secret
        - configMapRef:
            name: {{ template "chart.fullname" . }}-env-configmap
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: {{ include "chart.name" . }}-app-config-volume
        configMap:
          name: {{ include "chart.name" . }}-app-config
      nodeSelector:
        worker-type: application
