kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
{{- if .Values.httpClient.authPassword }}
  AUTH_PASSWORD: {{ required "A valid .Values.httpClient.authPassword entry required!" .Values.httpClient.authPassword | b64enc | quote }}
{{- end }}
{{- if .Values.eventStreams.consumer.sasl.password }}
  EVENT_SASL_PASSWORD: {{ required "A valid .Values.eventStreams.consumer.sasl.password entry required!" .Values.eventStreams.consumer.sasl.password | b64enc | quote }}
{{- end }}
{{- if .Values.defaults.secret }}
  DEFAULTS_USER_PASSWORD: {{ required "A valid .Values.defaults.secret entry required!" .Values.defaults.secret | b64enc | quote }}
{{- end }}
{{- if .Values.appId.tenantId }}
  APP_ID_TENANT_ID: {{ required "A valid .Values.appId.tenantId entry required!" .Values.appId.tenantId | b64enc | quote }}
{{- end }}
{{- if .Values.appId.clientId }}
  APP_ID_CLIENT_ID: {{ required "A valid .Values.appId.clientId entry required!" .Values.appId.clientId | b64enc | quote }}
{{- end }}
{{- if .Values.appId.iamKey }}
  APP_ID_IAM_KEY: {{ required "A valid .Values.appId.iamKey entry required!" .Values.appId.iamKey | b64enc | quote }}
{{- end }}
{{- if .Values.appId.clientSecret }}
  APP_ID_SECRET: {{ required "A valid .Values.appId.clientSecret entry required!" .Values.appId.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.keyProtect.iamKey }}
  KEYPROTECT_SERVICE_API_KEY: {{ required "A valid .Values.keyProtect.iamKey entry required!" .Values.keyProtect.iamKey | b64enc | quote }}
{{- end }}
